version: 0.2
phases:
  pre_build: 
    commands:
      - mv diff_target diff_target_old
      - git reset --hard HEAD
      - ls -al .
  build:
    commands:
      - echo これが表示されるだけ、のはずなんですがねぇ。しらんけど。
      - ls -al .
cache:
  paths:
    - diff_target/*
