version: 0.2
phases:
  build:
    commands:
      - diff ./change.txt ./last/change.txt || echo '変化あり'
  post_build:
    commands:
      - mkdir -p ./last
      - cp change.txt ./last/change.txt
cache:
  paths:
    - last/**/*
