version: 0.2
phases:
  pre_build: 
    commands:
      - echo 最初の時点で diff_target_old がどうなってるか
      - cat ./diff_target_old/change.txt
  build:
    commands:
      - echo これが表示されるだけ、のはずなんですがねぇ。しらんけど。
      - find .
      - cat ./diff_target_old/change.txt
      - date > ./diff_target_old/change.txt
cache:
  paths:
    - diff_target_old/change.txt
